### ISSUE TITLE
Pagination Broken

### ISSUE THREAD

**Issue by jakeanq** [mosra/magnum-website#9] opened 2019-01-04 07:31 UTC
Links to next and previous pages on paginated pages (for example on https://blog.magnum.graphics/ ) do not work as the URL becomes https://magnum.graphics/blog.magnum.graphics/2/ instead of https://blog.magnum.graphics/2/

**Comment by mosra** [comment] 2019-01-04 16:02
Thanks a lot for reporting this, very appreciated. Should be fixed now.

(For the record, turns out it was a regression in Pelican: https://github.com/getpelican/pelican/pull/2503)

**Closed as completed by mosra** 2019-01-04 16:02 UTC
